# Generated by Django 2.1.7 on 2020-10-29 05:43

from django.db import migrations, models
import uploadapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0005_file_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=uploadapp.models.location),
        ),
    ]
